node_js:
  - "0.10.31"
python:
  - '2.7'
notifications:
  email:
    - 47033631@qq.com
before_script:
  - echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - sudo pip install fabric
  - npm install
script:
  - echo 'Build Assets Files.'
#  - TODO: grunt.
after_success:
  - echo 'Ready to deploy distro to Linode server.'
  - fab setup deploy restart clean
  - echo 'Deploy entire site to production server finished!!!'
branches:
  only:
  - master
env:
  global:
  - secure: "inb3DRHKi6qFfmmP76qUO4dPHdsYVQRDGvDUb2hS0SLCrAOjG9wB/Y9BbjqXhGzkL0bvcaCqq4YzP8aNmyYs0Bpw5YT+el9do2ffIB6cALrfnnmsUpRto/43D51oeTf9VkFJYzPqGF15O/OVeZvLWVILk6RArW4ldJKPIFe0cdQ="
  - secure: "bsSfoNSyDj8tDPI9eqXybTJUt5UvQdjVgfrx+pvL7CejpQiQIziG9LB6y1Gn3QfB0WRaeB/v/Tm+G4yGJUOoB4ojXAHxwZo/4isDrYVnzuxnVDEhWXdWR2aknf5rrCG0IE5IHAg7OIXdsIdQ4sc21rmn0J7RZApVfCMG2gAdXZ4="
  - secure: "MkkVMv3p4FFjBrLw1Xz55FKG6j4XUMXByQkKDuFi1UWCYcZcQIMZFdr2GvQYbW2Gi8+3YVJWKdwnSpxjWauToM8o57BCfll3v0na8kZAQi+/UwGGruht5lQ5sLHTGMGram0c85LE291ZGkRdqqvZ5TrO9h+b4gxB8cOn2jHwDp8="
  - secure: "Oe9pixmq+pHjwGmZZtgX+QScmbShnRUyG9Sh2r6DAvG/sLKi/3Ffd7AX26b/I1snSuKI3vciDVbis2+/O5Ko9CLtHIcdCQIn6ENLO+eLJdL6a2F/E7Fm+YFF9W9c5T34+/MNxgWdtV2aeu2V5eeUQMSP5jQIVQZ3sl4xT2WjxMM="
  - secure: "TAmyTbs75yKB3P67ZnMpGLL7fDyXKHQ11070mh9avn2mI7S079bB80VQsygB8vWhFx+2ABX+G7qNTn3waBRnWElUFb1/bubO02MMdeOMz67/ua9Hjci6TdM8UgXGdu7V2XJLC1xAbGsuUqtVV+mZhh58ERMHWxcKPdserInr1No="
  - secure: "MdUHas7jD02ep2twARjra9j0fQkHktP0G6wQY6EH1KoOhDIafkCXxMSqSPSd/+otM82zy0U+cnN7MRuDi4sqErh3W+jPfD7ZD/dRoqZF2TuJcJgAxFyVEW2oXT5ug1RsjRv/FLBvPdZPjtAzQ6bZD4zMw13ojCgH7AVygXLXxdY="
  - secure: "dUrpQVGFAwl6EK7fAnxGD/AJbQbbLgx03NZaHnCspjs0wpNxg4rXit5dj4vHaeBQq6010UHZa2HMRfWMfmaSp73OtoG9cTSlF5v+1ApLQGZV1zYb+esbA5NO7httjWG6oyPK+ZpMrPXijdDuQHkRU/w/kVU1rr2n/3TteLBcWQM="
  - secure: "hwAQyLG6mjrpZraOMhfG7Bl5jRrJDGa5kRukuQcta7aBF3w5VEg8zA76++sMq18VTwXsISM40viYYTxiGBc2RCQ/OFcMJBiKEItkubHpRm094t3/XEb8rcSoIwrJXN9QOiIpIx1PASzmFi7pLhsbLbJGnkhz5X2dNI4FyA8fMno="
  - secure: "EFQPdwPI6G6g0JlTkazlKR4XV9Nl0+Dfc53LlQNYc8XdOMiMfiayyo0Ft3iU3vOUqW1KfRudeIuTlp8ZzC5gfamGgBxP5iLqZyeIy7kR7ECukRB+gyzdKS8ueoancE1tWM7VJF14zcTAe22o8s7PYgHFuSKr2MjICXDBLX6PZiY="
  - secure: "I6N6noYuQZ/YLzUvaIcEEIfok257W61zgJ2A1OI3gq2yj3023ZIaS3Uk9zxH8Q/owrKH4Ac6O9fOg5fwUL+Bd8P9H8LUAgAqKHfz2HDJPTWksu1QwvnRCGHDRYLc5MbAX5hNGR9svDuuuzKp88A31Be2qw2Ox+eJwoG05cljZA8="
  - secure: "pLWEAyNdreu8laX8hdA1yFTqKPyH9vSG9ElV4h7Pwym47rTGtQB82mIqwfMzeqjRqldzMe6MOHMOUIRk/ERf0eP3yzVl2gl3/65t0WzWJ/oPoaLRqMxDf+Jb7VHIKAUi5iwbxzneMSo3Gf0SuICCNSbEwl/JNn5nQLJ++Shk/DA="
  - secure: "WReL+TBqBwxxcQFDywqqUOcOKdsxGQi9keCohgRJm0OMFAJbKkfoUy6PrUa5A+/EqTTsLRHBl9o7kf7nZp5ZtPe4p47nnxbCKX0VKSgMsn7gJo1vyTSHCj9ZlmEsjkMkysnJIFoxiCsAqdxZ0pOYAJm89f2YCkYpdYqIMCIui9k="
  - secure: "bimJdN2JL7pTWzy28v2jI+sgzQh9jbdYCOM3i8ZhQDCpA7P9LdSR/6hZBrxajYdtMibWJkc8JnrLJss92i/rsHuNEtviiD0eZmslwSOiE3aQxQElmVn9RYEtxSISSOJfDr/3R1LCaAxcRYLLEyWXNpa02+nK+Ow9IX4Kryj8WLE="
  - secure: "HzwFwTvucsZvGx6JxjqR0/S80N5mPxXUbREtMPoY+NiRvSHe0dVOHPym3iFwoIucv5fdvV9Tjq9EesfTbkunhEDfmIv6nALU3V+td8Gn9KZ96eanVUoVEDqBBThU+Hezm7y3LW+FI9K3yWhcoGEhFtmz+zgKFjaZcKiEkFs+NFs="
  - secure: "E3pOw4y1QY4MNCK5N2Z2IvI2QqXeNtqxPJs+yl+MvXRKPJiORfuecvechLaAQ5CAfTUQpF5isiKH0ZuCMyVmSvoS1ysGZ9ZYHuellahwF/JdNga24wXDvu7/6MWTEUH6g2Mm7lmidDrMZG+BMiRv9ENFqGqCkVOOXp0ZgPEoWps="
  - secure: "Zptr4JsZwa7gsdrBBEOuOL4IBj4K503M5lkEcj24Il8NgDGsAZEVgwPSGRaq7fjdaimpmWbjY7THb9DuwxIqLCWSfqxsnafJJXGDOwhaKCU7M5ShVEpYVWf3sStuUsOL/2kE0yOpWIi1oXYq7Ps58DaZb8uiCoaWTywiSLHGUMA="
  - secure: "I18yqX4SuEOj1ZjNebqTZg0K8e4CeXr5R8oGCwh7aq/cWWO27qTd4C5Tv4hyhd8lQC9cip8Vm/Jq58eVuEVUrFg+Tno1/mAbga92CEvvlZQaY1UA8WD6mM9fLhO26RG+4bIgHNvYkq1mw7BVn0Mjf9YxSCskelGYy6DhIXhncRM="
  - secure: "J/2m7OGH/s4ZUpmoeKwvI1+gcHxHYzOpBSg5ovZJnNJG/2DmO5z5yd2afIl1UveCmE0zvVGrXT2BBkF40Z4oqYHH+cjcVtJtLse2lJmfsHWwlsSXrtYV4RqLvuLY2lxrybMs+rOEl2L51GbqdFf7Earc//Ce003jSgh2aXDXTl8="
  - secure: "iYly1RowBukHxZVJ2MgQvwT2JDJSVez75p0Pz6hpoMFyHJ8rm4+DNR1BecvsJGecxxA6CU1ifUI/OpOHBltayeTHj8/br2XY03OKGBWQnxZDGARXZvPnfR949qoYxBq535ocRI4SOF+JYyQpTw138BypUzEOvAo5WmIRxQVAxFo="
  - secure: "QJSnSJy4PrWZ4YQiq6wbiZ9xkTouePRmVjmuDWYNFTjniE1DwrTWqkvVMKXIQ4DvWaRgUZYUWpKs68QZtK8u2/BarHCzcEWaF95KmuBn3IyO7aHLmwz6CbxhEvlbul9kBy5PdMaoXoXWq9shu6oVzMjsIOvvNbmHIR5wCfqzd7M="
  - secure: "eM+KvC4MC/7A4qt2HP4ytcc3uHjAGgt0E1ttLtMz3iFbGU96VLJM+d9TrlqBWxrTQOUcPW6BYlRvH8CF3Muz27GJoabX+VKJkH7hnCE7J6idHdubyQcQ8YtQVVFMfnmcYbhKeSUubV/UkFSWCesPFc6ekwga+RrfylJEslNcKLE="
  - secure: "GcSq7baLuOQqWh30AMQZviqP94tM1LNtjVgphvSy+wkaS/QhgxPANzO+Fa0/hCbkqpAmP66BQLfn32beSls2xamjo+9nJE3CCRw0dfFZ35aQ0pukmtGm348kgpjXKrD7bCxY0bNLik0HTFSrV0SW5iaSmJSudIxfLEwq9wEOIzo="
  - secure: "fggvW06J5Do/Y28tLFFKPfVBdb6mvaz30srTptters32hthuzRsTiP+Qm/eAhXGKKSSryX8OrtEd/Gh7HNJYetoUeNDkA7ytEUL8rb+2eyF8Qm8Btz706skDd09tE1v5mUNCdS8Z91pgvyT/q+HnN0H5C1yqMdi816qHO1+iq6A="

