node_js:
  - "0.10"
python:
  - '2.7'
notifications:
  email:
    - 47033631@qq.com
before_script:
  - echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - sudo pip install fabric
  - npm install
script:
  - echo 'Build Assets Files.'
#  - TODO: grunt.
after_success:
  - echo 'Ready to deploy distro to Linode server.'
  - fab setup deploy restart clean
  - echo 'Deploy entire site to production server finished!!!'
branches:
  only:
  - master
env:
  global:
    - secure: "HkMDKddbCdSKgGo8WrJXlxZjQd320O29g0hkUE28555XIC/qQ7Qvd91sMCkmjusEsPd2rqYRWt3qyTD5BVyEatc5L1lEPezGYhRBCUqEBoXQ56LstaC6XA+eX7nrYfNa40cKcL8AT/k9UWD/oenxJxxFDDo01gHL9U3V84n7+X4="
    - secure: "IPH8SIzt5LC0xfPauMtGyvnOex9jdb2dNdNbcDe+INW0U+8R4zgmVGwQao8UxucLmX9LYKk2KaUp9OsA8bkvXW/lrPnI6BFJ27hCz0gortHgzT9UoCWt0t8WfW11GzlLYuS+6374LlSPZBDfIK2IBsCAldtfYlGiDsbx3z5nNhw="
    - secure: "N+YSmh7fsOvp4qNUSZjOueIodpbPJoM9XPHa+D0gLRkayJhzTkJl8KTijIPga6uM6XhTqM1JNsqT8GkfW9Ta8TB9P6J6yfjCW+X7a27/Cfrcdou/aoow5S3cJgc3zUHFIvtu4kLaJvu/lzt/RA5adDW2AJaOG4UjZwvtcdjCvm8="
    - secure: "TKPwMQcI7YfhugK+bwdfB8AvqPb56tjy+lSgISn54b4dgKco6hv1TQxhAPmvar6mhN6JVOzLLMcvFQZ3X2wDwGcQN4E2r0JH7+LqNYFO5FAq7DuE+1ykfTU2QpE58CAqTmTSjRWJHt1bjquH4s7avjVqkl7mCDfVY3bVHtqNAok="
    - secure: "WnO0W9QcUUs7myiDyrIbfld6K5Kzlu8G6tijgR9axaqUnMLr5+WwhWCX9SLGTH1QBO9fNYGQFWe21YTGM1LsP7x2d9zPTdfXxOf/sc26gCBs6l7PYc41ARY2vW6i4Z3YsOxb9UGwxdOWCjTL5muM8SmKWEmDOeYRJUB+b2iMErI="
    - secure: "diH2oe6lB6mdKRK053mdg8Vf2moscqKRDvphIcxIfmE01NQXHApbwi4TeK/ds7BHTDs4W1yWQfC+iDM6uBjXOdSUtczb4Xx8ShmGyS6hUhiCydj3Cdlka9HAcv2sv8kayTmhp4U8adv5s6bA0e3moWwiFPWKXwLONH5DLrtZjHY="

