node_js:
  - "0.10"
python:
  - '2.7'
notifications:
  email:
    - 47033631@qq.com
before_script:
  - echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - sudo pip install fabric
  - npm install
script:
  - echo 'Build Assets Files.'
#  - TODO: grunt.
after_success:
  - echo 'Ready to deploy distro to Linode server.'
  - fab setup deploy restart clean
  - echo 'Deploy entire site to production server finished!!!'
branches:
  only:
  - master
env:
  global:
  